// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqilwonehfptkqhlwkcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxaWx3b25laGZwdGtxaGx3a2NmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzA4NjMsImV4cCI6MjA2NDcwNjg2M30.09sQbdVjS4a1eJgIOvmoTtWSL9XkUufysHous7LgR2c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);